ethercalc:
  image: audreyt/ethercalc
  ports:
    - "8000:8000"
  environment:
    REDIS_PORT_6379_TCP_ADDR: redis
    REDIS_PORT_6379_TCP_PORT: 6379
  links:
    - redis:redis
  restart: always
redis:
  image: redis:latest
  volumes:
    - ./redis:/data
  command: redis-server --appendonly yes
  restart: always
